version: '3.4'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.3.2 
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  web:
    image: assurancetourix-web
    container_name: flask-container
    depends_on:
      - elasticsearch
    build:
      context: ./src/
      dockerfile: Dockerfile-server
    volumes: 
      - ./src/server:/src/server
      - rantanplan-volume:/src/rantanplan
    networks:
      - es-net
    ports:
      - 5002:5002

networks:
  es-net:
    driver: bridge

volumes:
    rantanplan-volume:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/rantanplan
      external: false