FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app
ADD . /app

RUN pip install -r requirements.txt

#Download all available Spanish corpora 
RUN averell download 1 2 3 5 6 --corpora-folder /corpora

#For development purposes
ENTRYPOINT ["tail", "-f", "/dev/null"]

# not really needed as the script will be run manually by the user 
# CMD ["python", "indexer.py"] 
